name: Say hello JAVI

on:
  push:
    branches:
      - main

jobs:
  hello_javi:
    runs-on: ubuntu-18.04
    steps:
      - name: Echo the message
        run: echo "Hola javi!"
      - name: Dime la fecha
        run: date
      - name: Lista archivos
        run: ls -l
